source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in cl-cars.gemspec
gemspec

gem 'require_all'
gem 'rspec'
gem 'pry'
gem 'nokogiri'
require 'open-uri'
